---
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org:
      springframework: INFO
management:
  server:
    address: 127.0.0.1
    port: 9001
spring:
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    swow-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver: org.postgresql.Driver
    tomcat:
      max-wait: 10000
      max-active: 25
      max-idle: 24
      min-idle: 1
      test-on-borrow: false
---
spring:
  profiles: dev
  spring:
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
  datasource:
    url: jdbc:postgresql://localhost/food_managment_db
    username: food_manager
    password : food_managment_db
server:
  port: ${8000:8080}
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://ec2-54-75-245-94.eu-west-1.compute.amazonaws.com/dchu7g5m9qqj7o
    username: csvafbqryklaww
    password : 9c260b7f80fa4b5431cfff4d11db60f2a05bf2fc775a958e2f8b0569d6ee8f9e
server:
  port: ${PORT:8080}
---
